### ISSUE TITLE
Gnome terminal plugin

### ISSUE THREAD

**Issue by jrock2004** [trevordmiller/nova-tmux#8]
**OS:**                      Ubuntu 17.04
**Terminal:**             Gnome Terminal 3.20.2-1
**Tmux Version:**     2.3-4

So I am trying to use the nova theme. When I am not in tmux, it looks perfect. When I load tmux, I get the following:

![image](https://user-images.githubusercontent.com/655716/29434264-567abb50-8370-11e7-9335-df0b26fd5c1a.png)

Here is my tmux

```
set -g default-command "login-shell"

# tmux display things in 256 colors
# set -g default-terminal "tmux-256color-italic"
set -g default-terminal "xterm-256color"

# enable terminal compability
set-option -ga terminal-overrides ",xterm-256color:Tc"

set -g history-limit 20000

# automatically renumber tmux windows
set -g renumber-windows on

# unbind default prefix and set it to Ctrl+a
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# for nested tmux sessions
bind-key a send-prefix

# Activity Monitoring
setw -g monitor-activity off
set -g visual-activity off

# Rather than constraining window size to the maximum size of any client
# connected to the *session*, constrain window size to the maximum size of any
# client connected to *that window*. Much more reasonable.
setw -g aggressive-resize on

# make delay shorter
set -sg escape-time 0

# tile all windows
unbind =
bind = select-layout tiled

# cycle through panes
# unbind C-a
# unbind o # this is the default key for cycling panes
# bind ^A select-pane -t:.+

# make window/pane index start with 1
set -g base-index 1
setw -g pane-base-index 1

set-option -g set-titles on
set-option -g set-titles-string "#T - #W"
# set-window-option -g automatic-rename on

######################
#### Key Bindings ####
######################

# reload config file
bind r source-file ~/.tmux.conf \; display "Config Reloaded!"

# quickly open a new window
bind N new-window

# split window and fix path for tmux 1.9
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# synchronize all panes in a window
bind y setw synchronize-panes

# pane movement shortcuts
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -r C-h select-window -t :-
bind -r C-l select-window -t :+

# Resize pane shortcuts
bind -r H resize-pane -L 10
bind -r J resize-pane -D 10
bind -r K resize-pane -U 10
bind -r L resize-pane -R 10

# set vi mode for copy mode
setw -g mode-keys vi
# more settings to make copy-mode more vim-like
unbind [
bind Escape copy-mode
unbind p
bind p paste-buffer

##############################
### Color & Style Settings ###
##############################

# source ~/.dotfiles/tmux/theme.sh

set -g default-terminal "xterm-256color"
set -ga terminal-overrides ",xterm-256color:Tc"
set -g pane-border-style 'bg=black,fg=#1E272C'
set -g pane-active-border-style 'bg=black,fg=#1E272C'
set -g status-style 'bg=#1E272C,fg=#6A7D89'
set-window-option -g window-status-current-bg '#1E272C'
set-window-option -g window-status-current-fg cyan
set -wg mode-style 'bg=cyan,fg=black'
set -g message-style 'bg=black,fg=cyan'
set -g clock-mode-colour cyan
```

**Comment by trevordmiller** [comment]
@jrock2004 Thanks for using Nova! If you could try a few things it will help us narrow down the issue:
1) Replace your tmux config with only the `nova-tmux` rules:
https://github.com/trevordmiller/nova-tmux/blob/master/assets/.tmux.conf#L6-L15

If this works, then it means that something in your tmux config is overriding so you can go through it line by line. If it still doesn't work, proceed:

2) Upgrade to latest tmux (`2.5`)
3) Upgrade to latest vim (`v8.0.09`)

If you are still seeing the issue after this, my only guess would be that Gnome Terminal has some special requirements or needs a separate color scheme or something when running with tmux but I don't use Gnome Terminal so I wouldn't know, I'm sorry. If you figure it out please let me know and I can add documentation to the website.

**Comment by trevordmiller** [comment]
@jrock2004 Also, you mentioned:

> "When I am not in tmux, it looks perfect"

Can you post a screenshot of this? I want to make sure it looks correct as Nova doesn't have a Gnome Terminal color scheme so I'm not sure how it would be working... 🤔

**Comment by jrock2004** [comment]
![image](https://user-images.githubusercontent.com/655716/29457789-fdd2187a-83e9-11e7-8267-bd743ecd0de9.png)

I have to run to work, but tonight I will try to upgrade tmux

**Comment by agarrharr** [comment]
@jrock2004 

I had trouble getting Nova to work in tmux on Gnome Terminal until I got tmux 2.5 and vim 8 installed. Nova is only working in vim for me. I don't think the nova colors will look right in tmux until you get a nova theme working in Gnome Terminal. Here is one approach to adding a theme: https://github.com/Anthony25/gnome-terminal-colors-solarized, and here is a collection of themes for Gnome Terminal: https://github.com/Mayccoll/Gogh. It might be good to add Nova to Gogh.

**Comment by trevordmiller** [comment]
@agarrharr @jrock2004 If either of you wants to build a Gnome Terminal Nova theme using nova-colors correctly (see the [Hyper](https://github.com/trevordmiller/nova-hyperterm) and [iTerm2](https://github.com/trevordmiller/nova-iterm) examples to see how you can use a build step to map the color values to color meanings), I'll happily add it to the website as an official plugin!

**Comment by agarrharr** [comment]
@trevordmiller I'll get started on it over at https://github.com/agarrharr/gnome-terminal-nova

**Comment by jrock2004** [comment]
@agarrharr You are thinking its due to the terminal theme for Gnome Terminal?

**Comment by agarrharr** [comment]
@jrock2004 Yes, I think so. If you look at the instructions for tmux on the nova website, the first step is "Install a Nova plugin for your terminal".

**Comment by trevordmiller** [comment]
@agarrharr Awesome! Thank you. Let me know when it is ready and I'll show you how to PR adding it to the website :)

**Comment by jrock2004** [comment]
So I got tmux 2.5 installed and ready to go

**Comment by trevordmiller** [comment]
@jrock2004 Ok, I'm closing this issue as it sounds like Gnome Terminal needs a plugin which @agarrharr will work on at https://github.com/agarrharr/gnome-terminal-nova and I'll add to the website once done.

**Comment by agarrharr** [comment]
I made [issue 1](https://github.com/agarrharr/gnome-terminal-nova/issues/1) over there so we can discuss progress.

**Comment by trevordmiller** [comment]
Added to Nova website in https://github.com/trevordmiller/trevordmiller-website/pull/106

**Comment by jacob-israel-turner** [comment]
I just started using tmux recently, and am trying to get nova to work here.  I at least want nova to work in vim within tmux.

I set up the Nova colors in Gnome Terminal myself, and tried to get this to work but had the same issues as @jrock2004.  I then used @agarrharr's `gnome-terminal-nova` solution. There is no difference.

Have ya'll actually fixed this?

**Comment by agarrharr** [comment]
@jacob-israel-turner You can make an issue over on [gnome-terminal-nova](https://github.com/agarrharr/nova-gnome-terminal/issues/new) and we can try to figure it out. I don't think @trevordmiller has GNU+Linux, but maybe @jrock2004 can help out with testing.

**Comment by jacob-israel-turner** [comment]
Thanks for the quick response @agarrharr, I found a solution here: https://github.com/tmux/tmux/issues/622

I had to switch `terminal-overrides` to `",screen-256color:Tc"` and `default-terminal` to `"screen-256color"`, which is different than the example tmuxconfig.

Thanks for your help!

**Comment by agarrharr** [comment]
Interesting, this is what I have:

```
# 256 color
set -g default-terminal "xterm-256color"

# Colors
set -ga terminal-overrides ",xterm-256color:Tc"
```

**Comment by jacob-israel-turner** [comment]
Whelp I don't know what's going on.  I just switched back to `xterm` and reset tmux, and it's working fine now.

Not sure if I had some odd setting earlier or something.

**Comment by trevordmiller** [comment]
@agarrharr Thanks for your help! @jacob-israel-turner it may have been that you had some saved state in a tmux session or something...anyways, glad you got it working!
