### ISSUE TITLE
Tmux Powerline

### ISSUE THREAD

**Issue by donifer** [trevordmiller/nova-tmux#9]
Hi, I know this is not related to this repo but I didn't know where else to ask.

I currently use Tmux with powerline and have everything setup with nova (iTerm, vim-airline, etc).

However I would like to have my tmux powerline to match my vim-airline. I thought `edkolev/tmuxline.vim` would do the job but I was mistaken.

This is how it looks right now:
<img width="694" alt="screen shot 2018-02-22 at 11 07 20 pm" src="https://user-images.githubusercontent.com/32689666/36578805-332c57f4-1825-11e8-860a-820ac063f09a.png">

Or if I force `:Tmuxline`
![image](https://user-images.githubusercontent.com/32689666/36578823-4e612f86-1825-11e8-874b-9c609b9ccfa9.png)

But none of them match. Would love some help/tips around this.

**Comment by trevordmiller** [comment]
Hey @donifer, no worries! I don't personally use powerline (it looks like tmux powerline has been deprecated, so I assume you are talking about [powerline](https://github.com/powerline/powerline)) and don't know many who do, so I don't think we'll add support to it to nova officially. But it looks like you can customize the colors using the tmux powerline docs:
- https://powerline.readthedocs.io/en/latest/configuration/reference.html#color-definitions
- https://powerline.readthedocs.io/en/latest/configuration/reference.html#colorschemes

So you should be able to use the [nova colors](https://github.com/trevordmiller/nova-colors/blob/master/src/index.js) manually in powerline.

Hope that helps!

**Comment by donifer** [comment]
You are a legend @trevordmiller thanks a lot!
